Install Git in Dockerfile
We need this to install Gems from GitHub:

```
6.383 Fetching https://github.com/DFE-Digital/dfe-analytics
6.396 You need to install git to be able to use gems from git repositories. For help
6.396 installing git, please refer to GitHub's tutorial at
6.396 https://help.github.com/articles/set-up-git
------
error: failed to solve: executor failed running [/bin/sh -c bundler -v &&     bundle config set no-cache 'true' &&     bundle config set no-binstubs 'true' &&     bundle config set without 'development test' &&     bundle install --retry=5 --jobs=4 &&     rm -rf /usr/local/bundle/cache]: exit code: 11
```